# Generated by Django 5.0.1 on 2024-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=100)),
                ('courttype', models.CharField(choices=[('G', '草地'), ('H', '硬地'), ('N', '泥地'), ('D', '地毯')], max_length=1)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
